### ISSUE TITLE
Data for each exercise

### ISSUE THREAD

**Issue by hankyul2** [I-Love-IU/chungyo#2]
**Problem**
Need to set rules to each exercise.

**Solution**
*StaticPose*
* [x] Initial Pose

*Exercise List*
* [x] walk
* [x] shoulder press
* [x] pull up

*Data for each exercise*
* [x] parts
* [x] pairs
* [x] accuracy 
* [x] starting_point

**Alternatives**

**Additional context**

**Comment by Rhcsky** [comment]
https://github.com/I-Love-IU/pose-difference/commit/ef2e4931d3837c1435105c143a8594310f132373#r35125942

**Comment by Rhcsky** [comment]
m_han/Common.py
sknefe

**Comment by Rhcsky** [comment]
sfsfs
