### ISSUE TITLE
Feature D : Tell different between two videos by FRAME

### ISSUE THREAD

**Issue by hankyul2** [I-Love-IU/chungyo#8]
**Problem**
Each video has a different playing time

**Solution**
Make the number of frames of two videos equal.
There are two main things and there are divided back into two or three.
1. *Increasing frame*
- [x] 3 way (round,round up, round down)
2. *Decreasing frame*
- [x] 3 way (round,round up, round down)
- [x] 2 way (average, non average)
So, we can get a total of 9 results.

*Remaining feature improvement*
We need to consider test case. There are three things I thought of.
1. Take a video ourselves from a different camera at the same location.
2. Use one skeleton but, the other one is simply reduced frames by drainage.
3. Take a video that we copy the trainer's video.

**Alternatives**

**Additional context**

**Comment by Rhcsky** [comment]
https://github.com/I-Love-IU/pose-difference/commit/3b957f7f86982a6fd9c14d8e33be4fc4f0c9b317#r35125883
